### ISSUE TITLE
设置一片空白，内详，感谢大佬，已经star

### ISSUE THREAD

**Issue by arraycto** [xerrors/Yuxi-Know#20]
![image](https://github.com/user-attachments/assets/d6367c55-488b-4de6-9f33-02f1ebaa6f60)

.env已经配置了大模型apikey，但是页面显示空白，如图。

**Comment by xerrors** [comment]
这种情况大概率是后端启动错误，可以使用 docker logs api-dev 看一下后端的启动情况。

**Comment by arraycto** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'src/config/models.yaml'

源码确实没有这个文件啊，需要自己创建么，大佬

**Comment by xerrors** [comment]
又忘记上传了，我更新一下，重新 git pull 一下就可以

**Comment by arraycto** [comment]
![image](https://github.com/user-attachments/assets/13b86df1-cde8-499b-aa06-91c856802650)
知识库有问题，大佬

**Comment by xerrors** [comment]
这个问题不是很好定位，可以尝试（1）先上传一个 txt 文件试试。（2）在 工具 中测试一下 pdf 转文本是否可以正常使用。

**Comment by arraycto** [comment]
![image](https://github.com/user-attachments/assets/fd76862c-9322-479f-89a3-93bd3cbf7fb3)
txt同样的效果哦

**Comment by xerrors** [comment]
看一下后端报错信息是哪里？

**Comment by xerrors** [comment]
可能是 zhipu-embedding 的长度限制问题，已经修改为轮询encoding，重新更新一下代码应该就可以了。

**Comment by xeon-ye** [comment]
Traceback (most recent call last):
  File "/opt/conda/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/uvicorn/main.py", line 412, in main
    run(
  File "/opt/conda/lib/python3.11/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/opt/conda/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/opt/conda/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/opt/conda/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/opt/conda/lib/python3.11/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/main.py", line 5, in <module>
    from src.routers import router
  File "/app/src/routers/__init__.py", line 2, in <module>
    from src.routers.chat_router import chat
  File "/app/src/routers/chat_router.py", line 7, in <module>
    from src.core.startup import startup
  File "/app/src/core/startup.py", line 26, in <module>
    startup = Startup()
              ^^^^^^^^^
  File "/app/src/core/startup.py", line 12, in __init__
    self.start()
  File "/app/src/core/startup.py", line 18, in start
    self.retriever = Retriever(self.config, self.dbm, self.model)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/core/retriever.py", line 15, in __init__
    self.reranker = Reranker(config)
                    ^^^^^^^^^^^^^^^^
  **_File "/app/src/models/embedding.py", line 33, in __init__
    model_name_or_path = config.model_local_paths.get(config.reranker, default_path=RERANKER_LIST[config.reranker])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: dict.get() takes no keyword arguments
Exception ignored in: <function AbsReranker.__del__ at 0x799ece763920>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/FlagEmbedding/abc/inference/AbsReranker.py", line 204, in __del__
AttributeError: 'Reranker' object has no attribute 'pool'_**
